# Point 4. LINCS-L1000 catalogue (GEO GSE92742) and the ccdata release used by retriever.
source('functions.R')
sink('results/01_lincs_metadata.txt', split = TRUE)
pert <- read.delim(gzfile('public/GSE92742_Broad_LINCS_pert_info.txt.gz'))
sig  <- read.delim(gzfile('public/GSE92742_Broad_LINCS_sig_info.txt.gz'))
cat('== GSE92742 (LINCS Phase I)\n')
cat('Perturbagens by type:\n'); print(table(pert$pert_type))
cat('Signatures:', nrow(sig), '\n')
cat('Cell lines with signatures:', length(unique(sig$cell_id)), '\n')
cp <- sig[sig$pert_type == 'trt_cp', ]
cat('Compounds with signatures:', length(unique(cp$pert_id)), '\n')
nCell <- tapply(cp$cell_id, cp$pert_id, function(x) length(unique(x)))
cat('Compounds profiled in 1 cell line:', sum(nCell == 1), '| in >= 10 cell lines:', sum(nCell >= 10), '\n')
cat('Compound signature time points:\n'); print(table(cp$pert_itime))
cat('Compounds with both 6 h and 24 h signatures:', sum(tapply(cp$pert_itime, cp$pert_id, function(x) all(c('6 h', '24 h') %in% x))), '\n')
nDose <- tapply(cp$pert_idose, cp$pert_id, function(x) length(unique(x)))
cat('Compounds with more than one dose:', sum(nDose > 1), sprintf('(%.1f%%)', 100 * mean(nDose > 1)), '\n')

cat('\n== ccdata l1000_es (all cell lines)\n')
suppressMessages(library(ccdata)); data('l1000_es', package = 'ccdata')
n <- gsub('\\[|\\]', '', colnames(l1000_es)); s <- strsplit(n, '_')
cat('Genes:', nrow(l1000_es), '| signatures:', ncol(l1000_es), '\n')
cat('Cell lines:', length(unique(sapply(s, function(X) X[length(X) - 2]))), '\n')
rm(l1000_es); invisible(gc())

cat('\n== ccdata, TNBC cell lines\n')
d <- loadTNBC(); md <- d$md
lig <- grepl('ng.ul', md$conc, fixed = TRUE)
cat('Signatures:', nrow(md), '| perturbagens:', length(unique(md$compound)), '\n')
cat('Perturbagens profiled in all three lines:', sum(tapply(md$cellLine, md$compound, function(x) length(unique(x))) == 3), '\n')
cat('Small molecules:', length(unique(md$compound[!lig])), '| ligands:', length(unique(md$compound[lig])), '\n')
cat('Small-molecule concentrations:', sort(unique(md$conc[!lig])), '| times:', sort(unique(md$time[!lig])), '\n')
cat('Ligand concentrations:', sort(unique(md$conc[lig])), '| times:', sort(unique(md$time[lig])), '\n')
sink()
