# Points 1 and 3. Leave-one-cell-line-out robustness of each method.
source('functions.R')
set.seed(1)
sink('results/04_stability.txt', split = TRUE)
d <- loadTNBC(); E <- d$E; md <- d$md; fc <- loadDisease(rownames(E))
subsets <- combn(TN, 2, simplify = FALSE)
S <- lapply(subsets, function(cl) allScores(E, md, fc, cells = cl)); names(S) <- sapply(subsets, paste, collapse = '+')
methods <- names(S[[1]])
common <- Reduce(intersect, lapply(methods, function(mt) Reduce(intersect, lapply(S, function(s) names(s[[mt]])))))
cat('Compounds scored by every method in every subset:', length(common), '\n')
out <- t(sapply(methods, function(mt){
  M <- sapply(S, function(s) s[[mt]][common])
  pr <- combn(3, 2)
  r <- apply(pr, 2, function(p) cor(M[, p[1]], M[, p[2]], method = 'spearman'))
  top <- apply(M, 2, function(s) common[order(s)][1:10])
  jac <- apply(pr, 2, function(p) length(intersect(top[, p[1]], top[, p[2]])) / length(union(top[, p[1]], top[, p[2]])))
  ql <- sapply(S, function(s) rank(s[[mt]])['QL-XII-47'])
  c(mean_rank_correlation = mean(r), min_rank_correlation = min(r), mean_top10_jaccard = mean(jac),
    QL_rank_min = min(ql), QL_rank_max = max(ql))
}))
print(round(out, 3))
cat('\nQL-XII-47 rank within each full subset ranking:\n')
print(sapply(methods, function(mt) sapply(S, function(s) unname(rank(s[[mt]])['QL-XII-47']))))
write.csv(out, 'results/stability_results.csv')
sink()
